-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/BlueSpiceRating/maintenance/db/sql/rating.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE bs_rating (
  rat_id SERIAL NOT NULL,
  rat_reftype VARCHAR(13) DEFAULT 'article' NOT NULL,
  rat_ref VARCHAR(33) DEFAULT '0' NOT NULL,
  rat_userid SMALLINT DEFAULT NULL,
  rat_userip VARCHAR(15) DEFAULT NULL,
  rat_value SMALLINT DEFAULT 0 NOT NULL,
  rat_created VARCHAR(14) DEFAULT '' NOT NULL,
  rat_touched VARCHAR(14) DEFAULT '' NOT NULL,
  rat_archived BOOLEAN DEFAULT 'false' NOT NULL,
  rat_subtype VARCHAR(33) DEFAULT '' NOT NULL,
  PRIMARY KEY(rat_id)
);

CREATE INDEX rat_userid ON bs_rating (rat_userid);

CREATE INDEX rat_userip ON bs_rating (rat_userip);

CREATE INDEX rat_ref ON bs_rating (rat_ref);

CREATE INDEX rat_reftype ON bs_rating (rat_reftype);
